from flask import Blueprint, jsonify, request
from flask_jwt_extended import get_jwt, get_jwt_identity, jwt_required

from ..models import Activity, AssistanceRequest, HomeVisit

bp = Blueprint("calendar", __name__, url_prefix="/api/calendar")

# Purely a read-aggregation over the three existing scheduling fields
# (HomeVisit.scheduled_at, AssistanceRequest.scheduled_at,
# Activity.scheduled_at) — no new model. Same role-scoping every other
# assignment-adjacent endpoint already uses: a volunteer only ever gets
# their own events, never another volunteer's/facilitator's, via the same
# assigned_to_id/facilitator_id == identity filter.


@bp.get("")
@jwt_required()
def list_calendar():
    role = get_jwt().get("role")
    identity = int(get_jwt_identity())

    visits_q = HomeVisit.query.filter(HomeVisit.scheduled_at.isnot(None))
    requests_q = AssistanceRequest.query.filter(AssistanceRequest.scheduled_at.isnot(None))
    # Activity.scheduled_at is non-nullable (always set on creation), unlike
    # the two queries above — no isnot(None) filter needed for it.
    activities_q = Activity.query

    if role == "volunteer":
        visits_q = visits_q.filter(HomeVisit.assigned_to_id == identity)
        requests_q = requests_q.filter(AssistanceRequest.assigned_to_id == identity)
        activities_q = activities_q.filter(Activity.facilitator_id == identity)
    elif role not in ("admin", "staff"):
        return jsonify(error="Forbidden"), 403

    start = request.args.get("start")  # YYYY-MM-DD, optional
    end = request.args.get("end")
    if start:
        visits_q = visits_q.filter(HomeVisit.scheduled_at >= start)
        requests_q = requests_q.filter(AssistanceRequest.scheduled_at >= start)
        activities_q = activities_q.filter(Activity.scheduled_at >= start)
    if end:
        visits_q = visits_q.filter(HomeVisit.scheduled_at <= end)
        requests_q = requests_q.filter(AssistanceRequest.scheduled_at <= end)
        activities_q = activities_q.filter(Activity.scheduled_at <= end)

    events = [
        {
            "id": v.id, "type": "home_visit",
            "elderly_member_id": v.elderly_member_id, "elderly_member_name": v.elderly_member.full_name,
            "assigned_to_id": v.assigned_to_id, "assigned_to": v.assigned_to.name if v.assigned_to else None,
            "scheduled_at": v.scheduled_at.isoformat(), "status": v.status,
            # New, additive field — null for a one-off visit, the parent
            # series' id for one generated by RecurringVisitSeries. Existing
            # consumers reading only the fields already documented above are
            # unaffected.
            "recurring_series_id": v.recurring_series_id,
        }
        for v in visits_q.all()
    ] + [
        {
            "id": r.id, "type": "assistance_request",
            "elderly_member_id": r.elderly_member_id, "elderly_member_name": r.elderly_member.full_name,
            "assigned_to_id": r.assigned_to_id, "assigned_to": r.assigned_to.name if r.assigned_to else None,
            "scheduled_at": r.scheduled_at.isoformat(), "status": r.status,
        }
        for r in requests_q.all()
    ] + [
        {
            # An Activity is a group event, not tied to one elderly member —
            # elderly_member_id/name are always null here (unlike the two
            # types above) and "title" carries the event's own name instead.
            # assigned_to_id/assigned_to reuse the same key names as the
            # other two types for a uniform shape, but point at the
            # facilitator, not an assignee.
            "id": a.id, "type": "activity",
            "elderly_member_id": None, "elderly_member_name": None, "title": a.title,
            "assigned_to_id": a.facilitator_id, "assigned_to": a.facilitator.name if a.facilitator else None,
            "scheduled_at": a.scheduled_at.isoformat(), "status": a.status, "activity_type": a.activity_type,
        }
        for a in activities_q.all()
    ]
    events.sort(key=lambda e: e["scheduled_at"])
    return jsonify(events=events), 200
