"""add phase7 admin security users sessions login history 2fa audit

Revision ID: 58c1f1169f7e
Revises: 68dba24f43e5
Create Date: 2026-08-31 19:32:12.083875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c1f1169f7e'
down_revision = '68dba24f43e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attempted_email', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_history_user_id'), ['user_id'], unique=False)

    op.create_table('totp_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_totp_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('two_factor_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('two_factor_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_two_factor_challenges_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_two_factor_challenges_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_refresh_jti'), ['refresh_jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default is required here — this table already has real
        # rows (existing users), and SQLite's batch ADD COLUMN NOT NULL
        # has no value to backfill them with otherwise. Dropped again
        # right after, since the model itself only defines these as
        # Python-side defaults (db.Column(..., default=...)), not
        # server-side ones — matches every existing row's actual value
        # while leaving future inserts to go through the model as usual.
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('active', server_default=None)
        batch_op.alter_column('totp_enabled', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_confirmed_at')
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('active')

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_refresh_jti'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('two_factor_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_two_factor_challenges_user_id'))
        batch_op.drop_index(batch_op.f('ix_two_factor_challenges_token'))

    op.drop_table('two_factor_challenges')
    with op.batch_alter_table('totp_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_totp_recovery_codes_user_id'))

    op.drop_table('totp_recovery_codes')
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_history_created_at'))

    op.drop_table('login_history')
    # ### end Alembic commands ###
