"""add donors campaigns expenses budgets audit_logs and donation linking

Revision ID: 68dba24f43e5
Revises: e8f94f950d36
Create Date: 2026-08-31 17:39:44.679816

"""
from collections import defaultdict
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68dba24f43e5'
down_revision = 'e8f94f950d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('organization', sa.String(length=150), nullable=True),
    sa.Column('donor_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donors_email'), ['email'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_program_id'), ['program_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('public_visible', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('vendor_name', sa.String(length=150), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_expense_date'), ['expense_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_program_id'), ['program_id'], unique=False)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('donor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_donations_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_donations_donor_id'), ['donor_id'], unique=False)
        batch_op.create_foreign_key('fk_donations_donor_id', 'donors', ['donor_id'], ['id'])
        batch_op.create_foreign_key('fk_donations_campaign_id', 'campaigns', ['campaign_id'], ['id'])

    # ### end Alembic commands ###

    _backfill_donors()


def _backfill_donors():
    """Cautious Donor backfill for existing Donation rows — one Donor
    per distinct normalized email, but ONLY when every donation sharing
    that email also shares the same donor name (case-insensitive,
    trimmed). Different names under the same email (a shared household/
    office inbox, a typo, two different people) are left donor_id=NULL
    for manual review rather than guessed at — this phase's explicit
    "do not silently merge donors when identity is uncertain" rule.
    Donations with no email at all are never auto-matched; nothing to
    key off of. Uses plain sa.table() reflections, not the real ORM
    models, so this migration never depends on how models.py evolves
    after it's written (same convention as e29a3d056e47's achievement
    seed insert)."""
    connection = op.get_bind()

    donations = sa.table(
        'donations',
        sa.column('id', sa.Integer), sa.column('donor_name', sa.String), sa.column('donor_email', sa.String),
        sa.column('donor_id', sa.Integer),
    )
    donors = sa.table(
        'donors',
        sa.column('id', sa.Integer), sa.column('name', sa.String), sa.column('email', sa.String),
        sa.column('donor_type', sa.String), sa.column('active', sa.Boolean),
        sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )

    rows = connection.execute(sa.select(donations.c.id, donations.c.donor_name, donations.c.donor_email)).fetchall()

    by_email = defaultdict(list)
    for row in rows:
        if row.donor_email:
            by_email[row.donor_email.strip().lower()].append(row)

    now = datetime.now(timezone.utc)
    linked_count = 0
    ambiguous_count = 0
    donors_created = 0

    for email, group in by_email.items():
        names = {r.donor_name.strip().lower() for r in group if r.donor_name}
        if len(names) != 1:
            ambiguous_count += len(group)
            continue

        result = connection.execute(
            donors.insert().values(
                name=group[0].donor_name.strip(), email=email, donor_type='Individual',
                active=True, created_at=now, updated_at=now,
            )
        )
        # sa.table()'s lightweight columns don't carry primary-key
        # metadata, so inserted_primary_key comes back empty — lastrowid
        # is the reliable cross-driver way to get the new id back on
        # SQLite, which is the only dialect this project's migrations
        # ever run against.
        donor_id = result.lastrowid
        donors_created += 1

        ids = [r.id for r in group]
        connection.execute(donations.update().where(donations.c.id.in_(ids)).values(donor_id=donor_id))
        linked_count += len(ids)

    print(
        f"[Phase 6 backfill] created {donors_created} donor(s), linked {linked_count} existing donation(s); "
        f"left {ambiguous_count} donation(s) unlinked for manual review (same email, differing donor name)"
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donations_campaign_id', type_='foreignkey')
        batch_op.drop_constraint('fk_donations_donor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_donations_donor_id'))
        batch_op.drop_index(batch_op.f('ix_donations_campaign_id'))
        batch_op.drop_column('donor_id')
        batch_op.drop_column('campaign_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_program_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_expense_date'))

    op.drop_table('expenses')
    op.drop_table('campaigns')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_program_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_resource')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('donors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donors_email'))

    op.drop_table('donors')
    # ### end Alembic commands ###
