"""add phase9 ai query log

Revision ID: 96e19091b196
Revises: efd7fc84ea77
Create Date: 2026-08-31 21:52:31.595210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e19091b196'
down_revision = 'efd7fc84ea77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=40), nullable=False),
    sa.Column('query_category', sa.String(length=40), nullable=True),
    sa.Column('resource_ids', sa.Text(), nullable=True),
    sa.Column('ai_used', sa.Boolean(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_query_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_ai_query_logs_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_query_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_query_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_query_logs_user_id'))
        batch_op.drop_index('ix_ai_query_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_ai_query_logs_created_at'))

    op.drop_table('ai_query_logs')
    # ### end Alembic commands ###
