"""add volunteer hours, achievements, training, documents

Revision ID: e29a3d056e47
Revises: eaff52e64e17
Create Date: 2026-08-31 11:39:35.968316

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa

# Deliberately importing application code from a migration — normally
# avoided in this app (see e.g. earlier migrations), but this specific
# import is inert, static Python data (a plain list of dicts, no model or
# ORM code), and needs to be the same single source of truth used by
# tests/conftest.py to seed the equivalent rows into the test database
# (which is built via db.create_all(), so this migration's own data step
# never runs there) — two independently-maintained copies drifting apart
# is a worse outcome than this import.
from app.achievements.seed_data import DEFAULT_ACHIEVEMENTS

# revision identifiers, used by Alembic.
revision = 'e29a3d056e47'
down_revision = 'eaff52e64e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('threshold_type', sa.String(length=30), nullable=False),
    sa.Column('threshold_value', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    achievements_table = sa.table(
        'achievements',
        sa.column('code', sa.String), sa.column('name', sa.String), sa.column('description', sa.Text),
        sa.column('icon', sa.String), sa.column('category', sa.String), sa.column('threshold_type', sa.String),
        sa.column('threshold_value', sa.Integer), sa.column('active', sa.Boolean), sa.column('created_at', sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(achievements_table, [{**row, 'active': True, 'created_at': now} for row in DEFAULT_ACHIEVEMENTS])

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_type'), ['owner_type'], unique=False)

    op.create_table('training_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('resource_url', sa.String(length=500), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['training_courses.id'], ),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'volunteer_profile_id', name='uq_training_progress')
    )
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_progress_volunteer_profile_id'), ['volunteer_profile_id'], unique=False)

    op.create_table('volunteer_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('awarded_by_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['awarded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_profile_id', 'achievement_id', name='uq_volunteer_achievement')
    )
    with op.batch_alter_table('volunteer_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_achievements_achievement_id'), ['achievement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteer_achievements_volunteer_profile_id'), ['volunteer_profile_id'], unique=False)

    op.create_table('volunteer_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_volunteer_hours_duration_positive'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_hours', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_hours_volunteer_profile_id'), ['volunteer_profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_hours_volunteer_profile_id'))

    op.drop_table('volunteer_hours')
    with op.batch_alter_table('volunteer_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_achievements_volunteer_profile_id'))
        batch_op.drop_index(batch_op.f('ix_volunteer_achievements_achievement_id'))

    op.drop_table('volunteer_achievements')
    with op.batch_alter_table('training_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_progress_volunteer_profile_id'))
        batch_op.drop_index(batch_op.f('ix_training_progress_course_id'))

    op.drop_table('training_progress')
    op.drop_table('training_courses')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_owner_type'))
        batch_op.drop_index(batch_op.f('ix_documents_owner_id'))

    op.drop_table('documents')
    op.drop_table('achievements')
    # ### end Alembic commands ###
