"""add programs activity_volunteers activity capacity document resource fields

Revision ID: e8f94f950d36
Revises: 55a06bd2b1a6
Create Date: 2026-08-31 16:28:19.750362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f94f950d36'
down_revision = '55a06bd2b1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('coordinator_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('target_population', sa.String(length=150), nullable=True),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coordinator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('activity_volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'volunteer_id', name='uq_activity_volunteer')
    )
    with op.batch_alter_table('activity_volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_volunteers_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_volunteers_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_volunteers_volunteer_id'), ['volunteer_id'], unique=False)

    # (PRAGMA foreign_keys is OFF for this whole migration run — see
    # migrations/env.py — because this batch op recreates `activities`,
    # which activity_participants and activity_volunteers hold live
    # foreign-key rows into.)
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registration_open', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_activities_program_id'), ['program_id'], unique=False)
        batch_op.create_foreign_key('fk_activities_program_id', 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('visibility')
        batch_op.drop_column('description')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_program_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activities_program_id'))
        batch_op.drop_column('registration_deadline')
        batch_op.drop_column('registration_open')
        batch_op.drop_column('capacity')
        batch_op.drop_column('program_id')

    with op.batch_alter_table('activity_volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_volunteers_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_activity_volunteers_assigned_at'))
        batch_op.drop_index(batch_op.f('ix_activity_volunteers_activity_id'))

    op.drop_table('activity_volunteers')
    op.drop_table('programs')
    # ### end Alembic commands ###
