"""add recurring visits, volunteer availability, incident assignment, staff notes

Revision ID: eaff52e64e17
Revises: f5d575e0403f
Create Date: 2026-08-31 10:22:31.411276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaff52e64e17'
down_revision = 'f5d575e0403f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_visit_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('occurrences_generated', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_visit_series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_visit_series_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_visit_series_elderly_member_id'), ['elderly_member_id'], unique=False)

    op.create_table('volunteer_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_availability_volunteer_profile_id'), ['volunteer_profile_id'], unique=False)

    op.create_table('volunteer_unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_profile_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_profile_id'], ['volunteer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_unavailability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_unavailability_volunteer_profile_id'), ['volunteer_profile_id'], unique=False)

    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_notes', sa.Text(), nullable=True))

    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_series_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_notes', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_home_visits_recurring_series_id'), ['recurring_series_id'], unique=False)
        # SQLite's batch (recreate-table) ALTER strategy requires a named
        # constraint, unlike a plain CREATE TABLE (where an unnamed FK is
        # fine) — this is the first migration in this repo that adds an FK
        # column to an already-existing table rather than a brand-new one,
        # which is why no earlier migration needed an explicit name here.
        batch_op.create_foreign_key('fk_home_visits_recurring_series_id_recurring_visit_series', 'recurring_visit_series', ['recurring_series_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_foreign_key('fk_incidents_assigned_to_id_users', 'users', ['assigned_to_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incidents_assigned_to_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incidents_assigned_to_id'))
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('home_visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_home_visits_recurring_series_id_recurring_visit_series', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_home_visits_recurring_series_id'))
        batch_op.drop_column('staff_notes')
        batch_op.drop_column('recurring_series_id')

    with op.batch_alter_table('assistance_requests', schema=None) as batch_op:
        batch_op.drop_column('staff_notes')

    with op.batch_alter_table('volunteer_unavailability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_unavailability_volunteer_profile_id'))

    op.drop_table('volunteer_unavailability')
    with op.batch_alter_table('volunteer_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_availability_volunteer_profile_id'))

    op.drop_table('volunteer_availability')
    with op.batch_alter_table('recurring_visit_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_visit_series_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_visit_series_assigned_to_id'))

    op.drop_table('recurring_visit_series')
    # ### end Alembic commands ###
