"""add phase8 geocoding consent family access distributions

Revision ID: efd7fc84ea77
Revises: 58c1f1169f7e
Create Date: 2026-08-31 20:27:35.429433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd7fc84ea77'
down_revision = '58c1f1169f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index('ix_consents_member_type', ['elderly_member_id', 'consent_type'], unique=False)

    op.create_table('family_member_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('relationship_label', sa.String(length=60), nullable=False),
    sa.Column('access_status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'elderly_member_id', name='uq_family_access_user_member')
    )
    with op.batch_alter_table('family_member_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_family_member_access_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_family_member_access_user_id'), ['user_id'], unique=False)

    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('elderly_member_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['elderly_member_id'], ['elderly_members.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_distributed_at'), ['distributed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_elderly_member_id'), ['elderly_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distributions_program_id'), ['program_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elderly_member_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_conversations_elderly_member_id', 'elderly_members', ['elderly_member_id'], ['id'])

    with op.batch_alter_table('elderly_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('geocode_source', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('geocode_accuracy', sa.String(length=20), nullable=True))

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meals_program_id'), ['program_id'], unique=False)
        batch_op.create_foreign_key('fk_meals_program_id', 'programs', ['program_id'], ['id'])

    with op.batch_alter_table('volunteer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_profiles', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meals_program_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meals_program_id'))
        batch_op.drop_column('program_id')

    with op.batch_alter_table('elderly_members', schema=None) as batch_op:
        batch_op.drop_column('geocode_accuracy')
        batch_op.drop_column('geocode_source')
        batch_op.drop_column('geocoded_at')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_conversations_elderly_member_id', type_='foreignkey')
        batch_op.drop_column('elderly_member_id')

    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_program_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_item_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_distributions_distributed_at'))

    op.drop_table('distributions')
    with op.batch_alter_table('family_member_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_family_member_access_user_id'))
        batch_op.drop_index(batch_op.f('ix_family_member_access_elderly_member_id'))

    op.drop_table('family_member_access')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consents_member_type')
        batch_op.drop_index(batch_op.f('ix_consents_elderly_member_id'))
        batch_op.drop_index(batch_op.f('ix_consents_created_at'))

    op.drop_table('consents')
    # ### end Alembic commands ###
